### ISSUE TITLE
🐛 [Bug report]: Stargazers not shown in the README

### ISSUE THREAD

**Issue by 6km** [reactplay/react-play#388]
**Describe the bug**
Stargazers not shown in the README

**Screenshot**
![image](https://user-images.githubusercontent.com/62352949/179752794-68125f2a-2f33-4a43-bdb2-ce922573eaec.png)

**Comment by atapas** [comment]
@6km depends on this: https://github.com/nastyox/Repo-Roster/issues/5

Btw, can we build something similar using JavaScript/Node?

**Comment by 6km** [comment]
I noticed that the developer has stopped supporting it since 2020, can we host it?

![image](https://user-images.githubusercontent.com/62352949/179754211-de4d7edb-7faa-4b09-8cb4-3f26c8ad7bf2.png)

I also think we can use [this endpoint ](https://api.github.com/repos/reactplay/react-play/stargazers?page=1) to build an alternative using node-canvas

**Comment by atapas** [comment]
Yes we can as it is opensource but it’s built on php, I do not have any idea how to deal with it. Any thoughts?

**Comment by atapas** [comment]
> Yes we can as it is opensource but it’s built on php, I do not have any idea how to deal with it. Any thoughts?

Also if the owner of the repo responds, we can see what help we can extend to make it up. It’s good for the community.

if no response, we can take the charge.

**Comment by atapas** [comment]
> It's good for the community. I hope he responds ASAP 🧐.

True, in the mean time, let’s explore options. You want to do some research, go ahead.

**Comment by 6km** [comment]
> You want to do some research

I will try to host it with 000webhost as it's the most popular free hosting. I will tell you once it's ready for use.

**Comment by 6km** [comment]
@atapas I couldn't host it with 000webhost it throws an error because 000webhost doesn't allow free members to install php extensions (it's something like the node.js packages)

```
Fatal error: Uncaught Error: Class 'Imagick' not found in /storage/-/-/-/public_html/stars.php:24 Stack trace: #0 {main} thrown in /storage/-/-/-/public_html/stars.php on line 24
```

do you know any php hosting that allows us to install extensions?

**Comment by atapas** [comment]
Super, can you apply it on our readme?

**Comment by 6km** [comment]
@atapas Unfortunately, I wasn't able to host it anywhere. I couldn't find any free hosting, I also tried hosting it on Vercel but it throws an error with the canvas, I couldn't find a fix for that error.

**Comment by 6km** [comment]
please tell me if you know any hosting options

**Comment by atapas** [comment]
> @atapas Unfortunately, I wasn't able to host it anywhere. I couldn't find any free hosting, I also tried hosting it on Vercel but it throws an error with the canvas, I couldn't find a fix for that error.

What’s the code based on? Have you tried on render? Is the repo link available to look into?

**Comment by atapas** [comment]
> please tell me if you know any hosting options

https://render.com/

**Comment by 6km** [comment]
> Is the repo link available to look into?

Yes, it's a public repo you can check it in my profile.

**Comment by atapas** [comment]
One question, is this service already hosted somewhere for us to use? Or we have to host only?

**Comment by 6km** [comment]
> One question, is this service already hosted somewhere for us to use? Or we have to host only?

I haven't hosted it yet because I wasn't able to find any free hosting. I will take a look at **Render**

**Comment by 6km** [comment]
@atapas It works now,

https://git-lister.onrender.com/api/stars/reactplay/react-play

**Comment by 6km** [comment]
There is an issue, the stargazers do not appear if you put the image in a GitHub readme. I don't know why this happens.

**Comment by atapas** [comment]
> There is an issue, the stargazers do not appear if you put the image in a GitHub readme. I don't know why this happens.

I see the service takes a while but return an image. What happen when you use it in Readme? What's the error? Btw, can we also limit the numbers we want to show?

**Comment by 6km** [comment]
> I see the service takes a while but return an image.

That's because I use canvas to draw a big amount of images, I will try to find a way to make it faster.

> What happen when you use it in Readme? What's the error?

It just doesn't appear, I have also tried to use the service in an online markdown editor and it appears.

> Btw, can we also limit the numbers we want to show?

I haven't added this ability yet, I will work on it.

**Comment by atapas** [comment]
> > I see the service takes a while but return an image.
> 
> That's because I use canvas to draw a big amount of images, I will try to find a way to make it faster.
> 
> > What happen when you use it in Readme? What's the error?
> 
> It just doesn't appear, I have also tried to use the service in an online markdown editor and it appears.
> 
> > Btw, can we also limit the numbers we want to show?
> 
> I haven't added this ability yet, I will work on it.

So does it work now?

One more enhancement we can add to it is, that it shows the recent stargazers first. That way the person who put a star now can see their photo immediately on the readme?

**Comment by 6km** [comment]
> So does it work now?

Yes, it works.

> that it shows the recent stargazers first

I have tried to implement this, but I couldn't 😥.

**Comment by atapas** [comment]
> > So does it work now?
> 
> Yes, it works.
> 
> > that it shows the recent stargazers first
> 
> I have tried to implement this, but I couldn't 😥.

I see. ok

Btw, I checked the readme on your forked repo, I see it broken. where can I test it before merge?


![image](https://user-images.githubusercontent.com/3633137/180191570-d15f7b50-e215-468b-af84-2d056bcd0d92.png)

**Comment by 6km** [comment]
> I checked the readme on your forked repo, I see it broken.

I updated the readme in [this branch](https://github.com/6km/react-play/tree/readme-stargazers-update), and it works.

**Comment by alexbelgium** [comment]
Works for me too here : https://github.com/alexbelgium/hassio-addons, thanks for developing this!

**Comment by 6km** [comment]
You're welcome, @alexbelgium . I hope you like it 💜.

**Comment by atapas** [comment]
> > I checked the readme on your forked repo, I see it broken.
> 
> I updated the readme in [this branch](https://github.com/6km/react-play/tree/readme-stargazers-update), and it works.

@6km is this the right place I am checking(take a look at the URL). It still doesn't appear for me :(

![image](https://user-images.githubusercontent.com/3633137/180353419-80abde3c-a7ad-4478-a3cf-9ebecd9b75ba.png)

**Comment by atapas** [comment]
> it appears for me, I think you can test it here (in issue comments).
> 
> ![](https://camo.githubusercontent.com/e850476c74e7208da43e8279bd27be2c0b87db9e500470bfffa15f71a6093fcf/68747470733a2f2f6769742d6c69737465722e6f6e72656e6465722e636f6d2f6170692f73746172732f7265616374706c61792f72656163742d706c61793f6c696d69743d3135)

Above also I am seeing as a broken image... any permission issue?

**Comment by atapas** [comment]
> this branch

I checked with Safari.. I see the similar issue there too.. Can you please post the link that you gave me yesterday for testing on our Discord tagging everyone? Let's test it out by others too.. I may be the only black sheep here :)

**Comment by 6km** [comment]
> I checked with Safari.. I see the similar issue there too.. Can you please post the link that you gave me yesterday for testing on our Discord tagging everyone? Let's test it out by others too.. I may be the only black sheep here :)

Sure
